### ISSUE TITLE
Missing template variables

### ISSUE THREAD

**Issue by zolotov** [bodiam/intellij-bootstrap#54]
```
No segment for variable: var=0; name=end; bs3-dismissable-alert:info

Template#name: Bootstrap3/bs3-dismissable-alert:info

Template#string: <div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
  <strong>Warning!</strong> Better check yourself, you're not looking too good.
</div>$END$
```

```
No segment for variable: var=0; name=end; bs3-alert-link

Template#name: Bootstrap3/bs3-alert-link

Template#string: <div class="alert alert-warning" role="alert">
   <strong>Warning!</strong> Better check yourself, you're <a href="#" class="alert-link">not looking too good</a>.
</div>$END$
```

Please test the rest templates.

**Comment by bodiam** [comment]
Hi @zolotov , thanks for reporting. Can you provide me with a bit more information on how to reproduce this? Also, which product are you using? I tried both templates, but they work fine for me.

Thanks, Erik

**Comment by zolotov** [comment]
I don't use any product, it's automatically reported the exception. To reproduce it just expand templates I described. The templates have more variables declared than their text contains.

**Comment by bodiam** [comment]
Hi @zolotov , thanks for the quick reply. What do you mean with: "expand templates"? You mean in the plugin settings? This is my plugin settings, and I don't see this issue. Where is this exception reported?

<img width="1204" alt="screen shot 2017-10-02 at 22 53 35" src="https://user-images.githubusercontent.com/46468/31076134-938e9ca0-a7c4-11e7-9d2a-ec1f6f93c913.png">

**Comment by bodiam** [comment]
I think I found (and fixed) what you meant. I'm still curious where you see this error though.

**Comment by zolotov** [comment]
The commit looks like a proper fix. The error will in editor when you try to use template

**Comment by bodiam** [comment]
I've never seen the error, and I'm curious to see why you get the error if you don't use any product (with product I mean IntelliJ, PHPStorm, something else), but maybe you're using a different version than me. I'll close the issue, if you see it again, please let me know!
