### ISSUE TITLE
bs3-form-select contains template for horizontal form insteed of normal

### ISSUE THREAD

**Issue by Antoniossss** [bodiam/intellij-bootstrap#55]
So currently bs3-form-select resolves to

```
                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <select class="form-control" id="">
                                        <option value=""></option>
                                    </select>
                                </div>
                            </div>
```

which is valid but ONLY for horizontal forms! (form.horizontal-form) https://getbootstrap.com/docs/3.3/css/#forms-horizontal
This should be changed to bs3-form-select-horizontal or similar variation.

Valid template is the one ommiting `col-xx-y` classes, so proper markup for standard form select is 

                            <div class="form-group">
                                <label for="" class=" control-label"></label>
                                <select class="form-control" id="">
                                    <option value=""></option>                                 
                                </select>
                            </div>
https://getbootstrap.com/docs/3.3/css/#forms-example
Normally i would not mind, but it breaks up when form is wrapped in smaller grid. 

Here is a screenshot and code for it
![obraz](https://user-images.githubusercontent.com/7877627/30511252-05b98044-9ad5-11e7-9aae-06890a702e46.png)

```
<div class="col-md-6">
                        <form method="post" th:object="${placeGenerationForm}">
                            <div class="form-group">
                                <label for="" class="control-label">Generation quantity</label>
                                <input type="number" max="1000" min="1" name="name" class="form-control"
                                       title=""
                                       required="required" th:field="*{count}" th:value="10">
                            </div>

                            <div class="form-group">
                                <label for="" class="control-label">City of places</label>
                                <select name="name" class="form-control"
                                        required="required" th:field="*{city}">
                                    <option value=""> -- Select One --</option>
                                    <option th:each="city : ${allCities}" th:value="${city.id}"
                                            th:text="${city.name}"/>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">Generation quanity</label>
                                <div class="col-sm-10">
                                    <input type="number" max="1000" min="1" name="name" class="form-control"
                                           title=""
                                           required="required" th:field="*{count}" th:value="10">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label">City of places</label>
                                <div class="col-sm-10">
                                    <select name="name" class="form-control"
                                            required="required" th:field="*{city}">
                                        <option value=""> -- Select One --</option>
                                        <option th:each="city : ${allCities}" th:value="${city.id}"
                                                th:text="${city.name}"/>
                                </div>
                            </div>
                        </form>

                    </div>
```

**Comment by bodiam** [comment]
Hi @Antoniossss , thanks for this amazing bug report, and my apologies for the delay in getting back to you! I checked the source code for `bs3-form-select`, but it's actually not in my code (see here: https://github.com/bodiam/intellij-bootstrap/blob/master/resources/liveTemplates/Bootstrap3.xml)

Are you sure this is not a template you've created yourself? I'm not sure where it's coming from to be honest.

If you want to have this shortcut in the plugin however, let me know, and I'll add it, but let's first figure out where it came from! :)

**Comment by Antoniossss** [comment]
My bad, as template name is actually **bs3-form-field:select**
![obraz](https://user-images.githubusercontent.com/7877627/31121779-db5bf06c-a839-11e7-8a0a-5a4b5f79ac26.png)

**Comment by bodiam** [comment]
Hi @Antoniossss , thanks. I've made the change, it now looks like this:

<img width="447" alt="screen shot 2017-10-03 at 23 11 15" src="https://user-images.githubusercontent.com/46468/31124456-3b80db96-a890-11e7-920b-2204c219378f.png">

Just checking if that's correct?

**Comment by Antoniossss** [comment]
Yes, looks just like in Bootstrap 3 documentation. Looking forward for update :)

**Comment by bodiam** [comment]
Great, thanks! I'll wait for the other issue, and then publish an update.
