### ISSUE TITLE
BS4 using alpha code

### ISSUE THREAD

**Issue by mwalker212** [bodiam/intellij-bootstrap#56]
Thanks for the BS4 update, much appreciated. Unfortunately, it looks like it's mostly from the BS alpha release as there have been some notable changes in the beta. e.g. card-block is now card-body etc.
There's a short-list of changes over here: https://medium.com/@lukaszholeczek/how-to-upgrade-bootstrap-4-alpha-6-to-bootstrap-4-beta-d43b4210f2a3

**Comment by bodiam** [comment]
Ah, thanks! I've fixed a few of the items, but not all of them have been
fixed. Do you have a list of the ones which are wrong? I'll fix them right
away!

**Comment by bodiam** [comment]
(in the meantime, I'm doing a fix with the link you've provided. Much
appreciated for that!)

**Comment by mwalker212** [comment]
Thanks. I've only just started playing with BS4 (at a client's request) so I'm only aware of the changes from the above link at the moment, and only because I tried the card and it didn't work right. I haven't tested much else yet. If I come across any other discrepancies I'll let you know.

**Comment by bodiam** [comment]
Hi, much appreciated! I just had a look at some other items, and it seems
the card section has been changed quite a bit, and it's not a
straightforward change, but I'm fixing it up right now. Thanks again for
reporting!

**Comment by bodiam** [comment]
Hi @mwalker212 , I've uploaded a new version of the plugin which fixes some of the issues. Also, I've added card support to the plugin. There might be more mission, if you encounter them, please let me know.

**Comment by mwalker212** [comment]
Thanks, I have found another small issue, in the modal header the title text should come before the close button as they are now displayed in the order they appear in the HTML, so in your template the close X is now on the left and the title on the right.

**Comment by bodiam** [comment]
Hi @mwalker212 , thanks again for reporting! If you say modal header, which template do you mean?

**Comment by mwalker212** [comment]
Any of the bs4-modal-xxx
They all produce the header sections as:
...
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="modelTitleId">Modal title</h4>
      </div>
...
The button and the h4 elements need to be transposed.

**Comment by bodiam** [comment]
Fixed in 4.0.4!
