### ISSUE TITLE
doesn't show up in IntelliJ IDEA Ultimate

### ISSUE THREAD

**Issue by orcpac7** [bodiam/intellij-bootstrap#65]
Installed Bootstrap 3 plugin version 4.1.1 in IntelliJ IDEA version 2020.2.1 Ultimate.

Typed `bs3-` and pressed CMD-J but only get the HTML completions, Nothing for bs3- or bs4-

Currently using Bootstrap 3 but planning to transition to Bootstrap 4 and this looked like a great tool to help.

**Comment by bodiam** [comment]
Hi @orcpac7 , I'm sorry to hear you have this issue. You might be able to import the live templates directly into IntelliJ without using the plugin. I've heard similar things before, but I can't reproduce it unfortunately.
